### ISSUE TITLE
Script throws Exception on MacOS

### ISSUE THREAD

**Issue by mrimann** [stirnim/hostname-check#1]
Running the script on a MacOS 10.16 El Capitan immediately throws an Exception before showing the usage help text:

```
➜  hostname-check git:(master) ./hostname-check.py
Traceback (most recent call last):
  File "./hostname-check.py", line 19, in <module>
    import dns.query
ImportError: No module named dns.query
```

Could you add to the README, what the recommended Environment and/or requirements are to have a base for running that script (well, for non Python experienced ones like me)

**Comment by stirnim** [comment]
fixed in https://github.com/stirnim/hostname-check/commit/1676a079104fdb54992af9a5261fbb4c8310db17

**Comment by mrimann** [comment]
Thanks!
